/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionproyectos.vista;

import PatronesDiseño.PrincipalVisitador;
import gestionproyectos.controlador.PrincipalController;
import gestionproyectos.modelo.Tareas;
import java.util.List;

/**
 *
 * @author gianlucasorem
 */
public class panel_modificar_tarea extends javax.swing.JPanel implements PrincipalVisitador{

    /**
     * Creates new form panel_modificar_tarea
     */
    public panel_modificar_tarea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nombre_tarea = new javax.swing.JLabel();
        txt_descripcion_tarea = new javax.swing.JLabel();
        button_realizada = new javax.swing.JRadioButton();
        button_incompleta = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        txt_nombre_tarea.setText("jLabel1");

        txt_descripcion_tarea.setText("jLabel1");

        button_realizada.setText("Realizada");

        button_incompleta.setText("Incompleta");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_realizada)
                                .addGap(67, 67, 67)
                                .addComponent(button_incompleta))
                            .addComponent(txt_descripcion_tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombre_tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButton1)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(txt_nombre_tarea)
                .addGap(37, 37, 37)
                .addComponent(txt_descripcion_tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_realizada)
                    .addComponent(button_incompleta))
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    if(button_realizada.isSelected() == true){
    PrincipalController.getInstance().modificarTareaTrue();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton button_incompleta;
    private javax.swing.JRadioButton button_realizada;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel txt_descripcion_tarea;
    private javax.swing.JLabel txt_nombre_tarea;
    // End of variables declaration//GEN-END:variables
   private PrincipalVisitador visitador;
   
public void cargarInformacion1(){
    
    Tareas tareaInfo = PrincipalController.getInstance().getTareaRealizar();
    txt_nombre_tarea.setText(tareaInfo.getNombreTarea());
    txt_descripcion_tarea.setText(tareaInfo.getDescripcionTarea());
    
    }

    @Override
    public void cambiarTarjeta(String tarjeta) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void CambiarTarjetaB(String tarjeta) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cargarInformacion() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cargarInformacion2() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cargarInformacion3() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setVisitador(PrincipalVisitador visitador) {
        this.visitador = visitador;
    }

}
